### ISSUE TITLE
Download page, and other stuff

### ISSUE THREAD

**Issue by Czapa10** [CaptainTimberTim/MPlay3#1]
Hi!

Could you create a place to download your application so people don't have to build the thing themselves?
You can for example use github Releases, itch.io or handmade network for that.

You could also add to the todo list:
- embed textures and fonts in executable, so you can just download an executable (not a zip), and you don't have to care about directory data being in one directory higher then executable.
- add icon
- make window title bar be something easier on the eyes then "(null)((null))"

I really like your project. I also couldn't find any decent mp3 player for windows.
I thought about writing my own but now it turns out I don't have to; so thanks and good luck.

**Comment by CaptainTimberTim** [comment]
thanks for the suggestions, I appreciate it!

I was on a bit of a hiatus from this project, but the suggestion of adding a Release is great and - already done - now.
And your other points are definitely things I will add to my to-do list and may tackle soon.
