### ISSUE TITLE
Bug - Program sometimes doesn't play next song from the list

### ISSUE THREAD

**Issue by Czapa10** [CaptainTimberTim/MPlay3#12]
Sometimes when the song ends the program doesn't play the next song.
The progress indicator just stops at the end of the progress bar.

**Comment by CaptainTimberTim** [comment]
Yes, this is a long-standing bug I thought I had fixed a number of times. 
As it is a threading issue between main and sound thread. Which is annoying to debug, as it happens so seldom.
But I already added some facilities to be able to exactly pinpoint it the next time it happens in the debugger.

I will update here when it's fixed.

**Comment by CaptainTimberTim** [comment]
So, I am pretty sure I found the cause of the bug, and it wasn't actually a thread timing bug...
It just really looked like one. 
But most likely I now have this one fixed and updated the latest release with that integrated. 
So if you downloaded the newest release already, before this message, then you should re-download it again.

If it ever stops randomly again, you can reopen the issue and I put it back on the bug-list. As it is really hard to be sure that it is actually fixed as it occurs so seldom.
