### ISSUE TITLE
URGENT: Crash when you change names of files

### ISSUE THREAD

**Issue by Czapa10** [CaptainTimberTim/MPlay3#13]
Program crashes oftentimes after you change the name of the song file while running the program or when you're opening the program after changing the name of the song file.
Then I have to delete the current library file so the application won't crash on startup.
I waste a lot of time because of this bug. Could you fix it?

**Comment by CaptainTimberTim** [comment]
I will look at it and try to fix it! Preferably this weekend.

**Comment by CaptainTimberTim** [comment]
So, I fixed a few things actually, that went wrong when renaming a file. Two of them leading to crashes.
But I could not replicate the crash-on-startup you mentioned. So I do not know if that is actually fixed now.

I will push a small release tomorrow with these fixes and a few smaller things I did over the last few weeks.

**Comment by CaptainTimberTim** [comment]
and I will leave this issue open for now. 
If you find that the bug is actually fixed after the release, you can close the issue. 
If not, maybe you can tell me the steps you take to provoke the crash-on-startup bug. That may help me to replicate it.

**Comment by Czapa10** [comment]
I suppose you fixed it.
