### ISSUE TITLE
Playlist duplication bug

### ISSUE THREAD

**Issue by Czapa10** [CaptainTimberTim/MPlay3#16]
When you rename a file that is on a playlist (other than the "All" playlist) and you press rescan button, the playlist gets duplicated.
![image](https://user-images.githubusercontent.com/39434914/135686861-98abf721-808e-4614-a24c-2b84910e9da3.png)

**Comment by CaptainTimberTim** [comment]
Will finally be fixed in the soon to be coming updated version.
