### ISSUE TITLE
Update 01.2 broke stuff.

### ISSUE THREAD

**Issue by Czapa10** [CaptainTimberTim/MPlay3#4]
The application now doesn't save/load color themes and layout of columns.
Names of songs now don't show up in the right column if files don't have metadata.
The window title is again (null) if the current song doesn't have metadata.

All of those bugs happen regardless of the location of .save files.

![image](https://user-images.githubusercontent.com/39434914/112731470-b229f700-8f37-11eb-853f-661c270342ce.png)

**Comment by CaptainTimberTim** [comment]
Mhhh.. that is strange.
I just downloaded the 01.2 release and tested everything and cannot replicate any of the bugs you mentioned.

The only thing that may interfere with saving that I can think about right not is that
1. Maybe you change the save files during program runtime, which would not work, as they get written on program exit.
2. The old save file (from prev. version) does not work anymore, as it was extended. That would prevent loading of settings.

I think in the near future I will upgrade the save file serialization, that wrong save file versions are not preventing the loading of older ones.

I don't know what happened when you tried the new release, but it could be that the library.save file is corrupt somehow, and thats why it does not show the names without metadata.

**Comment by Czapa10** [comment]
You're right. It was because I was trying to load files from the previous version.
It worked after I deleted the files and loaded the directory again.
Loading from %appdata% also works.

**Comment by CaptainTimberTim** [comment]
Great!
I will make sure to fix loading of the save files for the next release. 
I already had version numbers but did not really use them properly.
