### ISSUE TITLE
Replace "Play Next List" with "Temporary Playlist" 

### ISSUE THREAD

**Issue by Czapa10** [CaptainTimberTim/MPlay3#5]
Hi!
I like the Play Next List feature but you could make it even more useful.

You could make the Temporary Playlist column which would be on right from the Songs column.
The Temporary Playlist column would be visible only if it contains any songs.
You can add songs to it by clicking the button in the Songs column which previously was adding songs to Play Next List.
There would be a similar button on songs in Temporary Playlist which removes songs from the Temporary Playlist.
There would be also a button that clears the Temporary Playlist.
Temporary Playlist is better than Play Next List because you can randomize the order of songs and the list can loop after all chosen songs were played.

**Comment by Czapa10** [comment]
On the other hand Play Next List could stay because sometimes it's more convenient. For instance, if you wanna keep playing songs from the song list but you wanna just mark 1 or 2 songs that you wanna play next then adding them to Temporary Playlist and removing them from Temporary Playlist after they played would be a bit cumbersome.
Maybe it would sometimes make sense to use Play Next List in a fusion with Temporary Playlist.

I wonder what you think about the Temporary Playlist idea.
Regards,
RSVP

**Comment by Czapa10** [comment]
I guess you can easily create a "temporary" playlist with the new playlists feature and PlayNext list is still useful.
Although you could make PlayNext list more controllable. Button to get rid of all the songs on PlayNext list would be good for starters.

**Comment by CaptainTimberTim** [comment]
Yes, thats a good point. I will add something to control PlayNext a bit more.
